### ISSUE TITLE
backend: Routes on bidding  

### ISSUE THREAD

**Issue by notprowler** [notprowler/quickbid#13]
Bidding on Items
look at supabase tables
POST /api/bids - Submits a bid for a specific item, provided by a qualified user (U).
GET /api/bids/:item_id - Retrieves all bids for a particular item.
PUT /api/bids/:id/accept - Marks a bid as accepted, finalizing the deal with the buyer.
PUT /api/bids/:id/reject - Rejects a specific bid.

**Comment by notprowler** [comment]
// GET /api/users/:id - Fetches profile data for a specific user by their ID.
// DELETE /api/users/:id - Soft-deletes a user’s account (for deactivation or suspension).

**Comment by IvanC112** [comment]
Completed

**Comment by IvanC112** [comment]
Completed
